// Persian search aliases, keyed by the exact `name` field in drugs-data.js.
// Lets the pharmacist search in Farsi even though the database stores
// international drug names.
export const ALIASES = {
  "ACETAMINOPHEN": ["استامینوفن", "پاراستامول", "تب بر"],
  "ACETAMINOPHEN / CHLORPHENIRAMINE / DEXTROMETHORPHAN / PHENYLEPHRINE": ["سرماخوردگی", "استامینوفن کدکس"],
  "ACETAMINOPHEN / DIPHENHYDRAMINE / PHENYLEPHRINE": ["سرماخوردگی شبانه"],
  "ACETAMINOPHEN / GUAIFENESIN / PHENYLEPHRINE": ["سرماخوردگی"],
  "Acyclovir": ["آسیکلوویر", "زونا", "تبخال", "آبله مرغان"],
  "COLD PREPARATIONS": ["سرماخوردگی بزرگسال"],
  "ALUMINIUM HYDROXIDE / MAGNESIUM HYDROXIDE": ["آنتی اسید", "سوزش معده"],
  "Amoxicillin": ["آموکسی سیلین", "آنتی بیوتیک"],
  "Amoxicillin (فاراموکس BD)": ["آموکسی سیلین", "فاراموکس"],
  "AZITHROMYCIN": ["آزیترومایسین", "زیترومکس", "آنتی بیوتیک"],
  "BACLOFEN": ["باکلوفن", "شل کننده عضله"],
  "CARBAMAZEPINE": ["کاربامازپین", "تگرتول", "ضد تشنج"],
  "Cefalexin": ["سفالکسین", "آنتی بیوتیک"],
  "Cefixime": ["سفیکسیم", "آنتی بیوتیک"],
  "CEFUROXIME (AS AXETIL)": ["سفوروکسیم", "آنتی بیوتیک"],
  "Cephalexin": ["سفالکسین", "آنتی بیوتیک"],
  "CETIRIZINE HYDROCHLORIDE": ["ستیریزین", "آلرژی", "ضد حساسیت"],
  "CHLOROQUINE": ["کلروکین", "ضد مالاریا"],
  "CHLORPHENIRAMINE MALEATE": ["کلرفنیرامین", "آلرژی"],
  "CHOLESTYRAMINE": ["کلستیرامین", "چربی خون"],
  "CIMETIDINE": ["سایمتیدین", "زخم معده"],
  "CIPROFLOXACIN": ["سیپروفلوکساسین", "آنتی بیوتیک"],
  "CITALOPRAM": ["سیتالوپرام", "افسردگی"],
  "Clarithromycin": ["کلاریترومایسین", "آنتی بیوتیک"],
  "CLINDAMYCIN (AS PALMITATE HYDROCHLORIDE)": ["کلیندامایسین", "آنتی بیوتیک"],
  "CODEINE PHOSPHATE / GUAIFENESIN": ["کدئین", "سرفه"],
  "CoAmoxicalve 4:1": ["کوآموکسی کلاو", "آگمنتین", "آنتی بیوتیک"],
  "CoAmoxicalve 7:1": ["کوآموکسی کلاو", "آگمنتین", "آنتی بیوتیک"],
  "CoAmoxicalve 14:1": ["کوآموکسی کلاو", "آگمنتین", "آنتی بیوتیک"],
  "CoTRIMOXAZOLE": ["کوتریموکسازول", "باکتریم", "آنتی بیوتیک"],
  "CYPROHEPTADINE HYDROCHLORIDE": ["سیپروهپتادین", "اشتها آور", "میگرن"],
  "DESLORATADINE": ["دسلوراتادین", "آلرژی"],
  "DEXAMETHASONE": ["دگزامتازون", "کروپ"],
  "DEXTROMETHORPHAN / GUAIFENESIN": ["دکسترومتورفان", "سرفه"],
  "DEXTROMETHORPHAN / GUAIFENESIN / PHENYLEPHRINE": ["دکسترومتورفان", "سرفه و سرماخوردگی"],
  "DEXTROMETHORPHAN / PSEUDOEPHEDRINE": ["دکسترومتورفان", "سرفه و سرماخوردگی"],
  "DEXTROMETHORPHAN HYDROBROMIDE": ["دکسترومتورفان", "سرفه"],
  "DIPHENHYDRAMINE ": ["دیفن هیدرامین", "خواب آور", "آنتی هیستامین"],
  "DIPHENHYDRAMINE / AMMONIUM CHLORIDE": ["دیفن هیدرامین", "سرفه و سرماخوردگی"],
  "DOMPERIDONE": ["دومپریدون", "تهوع", "استفراغ"],
  "Erythromycin": ["اریترومایسین", "آنتی بیوتیک"],
  "EXPECTORANT": ["خلط آور", "سرفه"],
  "EXPECTORANT CODEINE": ["خلط آور کدئین دار", "سرفه"],
  "FAMOTIDINE": ["فاموتیدین", "زخم معده", "ریفلاکس"],
  "FEXOFENADINE HYDROCHLORIDE": ["فکسوفنادین", "آلرژی"],
  "FLUCONAZOLE": ["فلوکونازول", "ضد قارچ"],
  "FURAZOLIDONE": ["فورازولیدون", "ژیاردیازیس"],
  "GUAIFENESIN": ["گایافنزین", "خلط آور"],
  "HYDROXIZINE": ["هیدروکسی زین", "آلرژی", "خارش"],
  "IBUPROFEN": ["ایبوپروفن", "مسکن", "تب بر"],
  "KETOTIFEN (AS FUMARATE)": ["کتوتیفن", "آلرژی", "آسم"],
  "L-CARNITINE": ["ال-کارنیتین"],
  "LACTULOSE": ["لاکتولوز", "یبوست"],
  "LOPERAMIDE HYDROCHLORIDE": ["لوپرامید", "اسهال"],
  "LORATADINE": ["لوراتادین", "کلاریتین", "آلرژی"],
  "MAGNESIUM HYDROXIDE": ["منیزیم هیدروکساید", "شربت شیر منیزی", "یبوست"],
  "METRONIDAZOLE (AS BENZOATE)": ["مترونیدازول", "فلاژیل", "آنتی بیوتیک"],
  "OMEPRAZOLE (kidizole)": ["امپرازول", "کیدیزول", "زخم معده", "ریفلاکس"],
  "ONDANSETRON": ["اندانسترون", "تهوع", "استفراغ"],
  "ORS": ["او آر اس", "کم آبی", "اسهال"],
  "PEDIATRIC GRIPPE": ["گریپ کودکان", "سرماخوردگی"],
  "PENICILLIN V (AS POTASSIUM)": ["پنی سیلین", "آنتی بیوتیک"],
  "PENICILLIN V BENZATHINE": ["پنی سیلین", "آنتی بیوتیک"],
  "PHENYTOIN": ["فنی توئین", "ضد تشنج"],
  "PROMETHAZINE": ["پرومتازین", "تهوع مسافرت", "خواب آور"],
  "PSEUDOEPHEDRINE HYDROCHLORIDE": ["سودوافدرین", "احتقان بینی"],
  "SIMETHICONE (DIMETHICONE ACTIVATED)": ["سایمتیکون", "نفخ", "دل درد نوزاد"],
  "THEOPHYLLINE / GUAIFENESIN": ["تئوفیلین", "آسم"],
  "VITAMIN D3": ["ویتامین د", "آ+د"],
  "Calcium": ["کلسیم"],
};
